### ISSUE TITLE
grepmenu fails with certain inputs

### ISSUE THREAD

**Issue by dgrisham** [lenormf/kakoune-extra#12]
The `:grepmenu` command seems to fail on certain inputs. Seems to be an issue with escaping quotes. For example, with the file:

```
'--pass'
```

`:grepmenu pass` gives the error:

```
Error: 1:1: 'grepmenu' 1:2: 'evaluate-commands' parse error: unterminated string '...'
```

I don't really know `awk` and haven't tried to debug this much further, but hopefully that's enough information to start with.

**Comment by lenormf** [comment]
Thanks for reporting the issue, I'll look into it. I think this file needs a little refactoring to leverage the new escaping syntax.
