### ISSUE TITLE
idsession.kak

### ISSUE THREAD

**Issue by leiserfg** [lenormf/kakoune-extra#13]
Use autogenerated sessionid for generating the human-friendly one instead of rand.

**Comment by lenormf** [comment]
Could you clarify what you mean by that?

**Comment by leiserfg** [comment]
Probably this weekend I'll do a pull request, code speaks clear than me.

**Comment by lenormf** [comment]
I think I understand now, it's a good idea.

You want to use the number that's used as a session name by default to pick one from the array, right?

**Comment by leiserfg** [comment]
Yes, that is my idea.

**Comment by lenormf** [comment]
That's implemented, you can now set the list of adjectives/nouns used by the command, also don't forget to add the following to your configuration:

```
hook global KakBegin .* idsession
```
