### ISSUE TITLE
Buffer wiped by syntax errors on save

### ISSUE THREAD

**Issue by melboyce** [lenormf/kakoune-extra#4]
If there's a syntax error in a Go file and `syntastic_autoformat` is set to `yes`, the buffer will be wiped as `gofmt` replaces its normal output of the source with the error message. I assume I'm not alone, but must be missing some kind of workflow or extra `.kakrc` scaffolding.

**Comment by casimir** [comment]
That's the reason why there is a go-specific format function (https://github.com/mawww/kakoune/blob/master/rc/extra/go-tools.kak#L56). IMHO this is a problem with `:format` not handling errors correctly.
Maybe you should report it directly on [kakoune's repo](https://github.com/mawww/kakoune/issues/new).

I use `hook buffer BufWritePre .+\.go %{ go-format -use-goimports }` BTW.

**Comment by melboyce** [comment]
Closing as per request. See: https://github.com/mawww/kakoune/issues/1357
