### ISSUE TITLE
Feature request: rubocop for syntastic

### ISSUE THREAD

**Issue by BjornMelgaard** [lenormf/kakoune-extra#5]
Please)

**Comment by lenormf** [comment]
I had tried including it by default, but I think it couldn't work with `lint` at the time so I ignored it. I don't use ruby, so I'm closing this issue, but I'll merge any PR that would provide support for `rubocop`.

**Comment by BjornMelgaard** [comment]
What the problem with lint?

**Comment by lenormf** [comment]
You need to be able to format the output of errors printed by the linter so that the `:lint` command can parse, I think I found at the time that you couldn't do that with `rubocop`.

**Comment by BjornMelgaard** [comment]
[Difference between formats shellcheck that syntastic use and rubocop](https://gist.github.com/BjornMelgaard/b636b45ce042872ddfe1f3b19cce0280#file-sintastic-L11) 

Are you saying that lint cant consume CRW error codes, but only note, error, warning?
Maybe its possible to use [wrapper script](https://github.com/BjornMelgaard/dotfiles/blob/master/bin/rubocop-wrapper.sh)? [Plug](https://github.com/BjornMelgaard/dotfiles/blob/master/kak/kakrc#L41)
But it doesnt work, are syntastic require RELATIVE filepath?
